module.exports = {
  ALERT: 'ALERT',
  LOG: 'LOG',
  CONNECT_NODE: 'CONNECT_NODE',
  SEND_TRANSACTION: 'SEND_TRANSACTION',
  DAPP_PERMISSIONS: 'DAPP_PERMISSIONS',
  EDIT_ADDRESS: 'EDIT_ADDRESS',
  EDIT_BOOKMARK: 'EDIT_BOOKMARK',
  ADDRESS_QR: 'ADDRESS_QR',
  EDIT_TOKEN: 'EDIT_TOKEN'
}
