module.exports = {
  DEFAULT_GAS_LIMIT: 21000,
  ETH: 'ETH',
  TRANSACTION_TYPE: {
    ETH_TRANSFER: 'ETH_TRANSFER',
    TOKEN_TRANSFER: 'TOKEN_TRANSFER',
    CONTRACT_CALL: 'CONTRACT_CALL',
    CONTRACT_CREATION: 'CONTRACT_CREATION'
  },
  TRANSACTION_STATUS: {
    ACCEPTED: 'ACCEPTED',
    REJECTED: 'REJECTED'
  }
}
