export const LOAD_CONFIG = 'LOAD_CONFIG'
export const OPEN_EXTERNAL_URL = 'OPEN_EXTERNAL_URL'
export const FETCH_SAFE_GAS_PRICE = 'FETCH_SAFE_GAS_PRICE'
export const CHECK_FOR_UPDATE = 'CHECK_FOR_UPDATE'
