# Uncomment this line to define a global platform for your project
  platform :ios, '8.0'

  target 'meth' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # pod 'Mixpanel', '~> 3.1'
    # pod 'Instabug'

    target 'methTests' do
      inherit! :search_paths
      # Pods for testing
    end

  end
