# Uncomment this line to define a global platform for your project
  platform :ios, '8.0'

  target 'meth' do
    # Uncomment this line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!

    # pod 'Mixpanel', '~> 3.1'
    # pod 'Instabug'

    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
      'RCTActionSheet',
      'RCTAnimation',
      'RCTGeolocation',
      'RCTImage',
      'RCTLinkingIOS',
      'RCTNetwork',
      'RCTSettings',
      'RCTText',
      'RCTVibration',
      'RCTWebSocket',
      'DevSupport'
    ]
    pod 'RNSVG', :path => '../node_modules/react-native-svg'
    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

    target 'methTests' do
      inherit! :search_paths
      # Pods for testing
    end

  end
