#!/bin/bash
set -e
rm -rf build-tools/data/ios.assets
mkdir -p build-tools/data/ios.assets
node_modules/.bin/react-native bundle --platform ios --entry-file index.ios.js --bundle-output build-tools/data/ios.assets/main.jsbundle --assets-dest build-tools/data/ios.assets --dev false
