module.exports = {
  net_version: { shareable: true },
  net_listening: { shareable: true },
  net_peerCount: { shareable: true },
  eth_protocolVersion: { shareable: true },
  eth_syncing: { shareable: true },
  eth_mining: { shareable: true },
  eth_gasPrice: { shareable: true },
  eth_hashrate: { shareable: true },
  eth_blockNumber: { shareable: true },
  eth_getBalance: { shareable: true },
  eth_getStorageAt: { shareable: true },
  eth_getTransactionCount: { shareable: true },
  eth_getBlockTransactionCountByHash: { shareable: true },
  eth_getBlockTransactionCountByNumber: { shareable: true },
  eth_getUncleCountByBlockHash: { shareable: true },
  eth_getUncleCountByBlockNumber: { shareable: true },
  eth_getCode: { shareable: true },
  eth_sendRawTransaction: {},
  eth_call: {},
  eth_estimateGas: {},
  eth_getBlockByHash: { shareable: true },
  eth_getBlockByNumber: { shareable: true },
  eth_getTransactionByHash: { shareable: true },
  eth_getTransactionByBlockHashAndIndex: { shareable: true },
  eth_getTransactionByBlockNumberAndIndex: { shareable: true },
  eth_getTransactionReceipt: { shareable: true },
  eth_getUncleByBlockHashAndIndex: { shareable: true },
  eth_getUncleByBlockNumberAndIndex: { shareable: true },
  eth_getLogs: { shareable: true },
  eth_getWork: { shareable: true },
  eth_getCompilers: { shareable: true },
  eth_submitWork: {},
  eth_submitHashrate: {}
}
